name: najnaj

services:
  # Servis za Flask backend aplikaciju
  flask:
    container_name: najnaj-flask-container
    build:
      context: .
      dockerfile: Dockerfile.flask
    env_file:
      - .env
    networks:
      - najnaj-network
    ports:
      - "5000:5000"
    volumes:
      # Povezuje ceo korenski direktorijum projekta sa /app u kontejneru
      - .:/app
      - najnaj-flask-volume:/app/dataBase
    restart: unless-stopped
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Servis za Tailwind CSS frontend
  tailwind:
    container_name: najnaj-tailwind-container
    build:
      context: .
      dockerfile: Dockerfile.tailwind
    networks:
      - najnaj-network
    volumes:
      # Takođe povezuje ceo korenski direktorijum projekta sa /app
      - .:/app
    cpus: 0.5
    cap_drop:
      - ALL

networks:
  najnaj-network:
    driver: bridge

volumes:
  najnaj-flask-volume:

